# Generated by Django 3.1 on 2020-08-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teapack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cost', models.PositiveSmallIntegerField(default=0, verbose_name='Стоимость товара')),
                ('odlcost', models.PositiveSmallIntegerField(default=0, verbose_name='Старая цена')),
                ('sale', models.PositiveSmallIntegerField(default=0, verbose_name='Скидка')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('image', models.ImageField(upload_to='media/', verbose_name='Миниатюра товара')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('likestate', models.BooleanField(default=False, verbose_name='Лайк')),
            ],
        ),
    ]
