# Generated by Django 3.1 on 2020-08-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teapack',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='teapack',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Миниатюра товара'),
        ),
        migrations.AlterField(
            model_name='teapack',
            name='odlcost',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='teapack',
            name='sale',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='teapack',
            name='url',
            field=models.SlugField(max_length=160, null=True, unique=True),
        ),
    ]
