# Generated by Django 3.1 on 2020-08-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teashop', '0002_auto_20200815_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teapack',
            name='odlcost',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='teapack',
            name='sale',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Скидка'),
        ),
    ]
